### ISSUE TITLE
Not recommended to use js.erb

### ISSUE THREAD

**Issue by ankitkalia1195** [rafayet-monon/google-search-extractor#28]
https://stackoverflow.com/questions/34639266/why-js-erb-is-so-bad

If we really want to build a good UI, we should go with regular javascript, not using js.erb. Even regular UI with no javascript and simple redirections can work for this excercise, but if you really want to showcase good UI with javascript, you should be using regular javascript not js.erb.

**Comment by rafayet-monon** [comment]
Thanks for pointing it out. Didn't know that this kind of opinions existed and seems like a fair opinion to me. So I will just stick to simple UI and redirects for now. Changes are merged to master and reflected in [heroku](https://search-extractor.herokuapp.com/search_files/new) too. Let me know if you feel there's room for more better changes. Till then will keep this one open.

**Comment by ankitkalia1195** [comment]
Sure, closing the issue.
